apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: tp-ns
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-tempconverter-service
  namespace: tp-ns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: web
  selector:
    app: traefik
